version: '3.9'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: manager_db
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: manager_ui/backend/Dockerfile
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db/manager_db
      TELEGRAM_BOT_TOKEN: your_token_here
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: manager_ui/frontend/Dockerfile
    ports:
      - "8080:80"

volumes:
  db_data:
